name: release

on:
  push:
    branches-ignore:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: apple-actions/import-codesign-certs@v1
      with: 
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
    - name: update version
      run: |
        PRODUCT_SETTINGS_PATH=./hw/Info.plist
        version=$(git describe --tags `git rev-list --tags --max-count=1`)
        vv=`date "+%Y%m%d%H%M%S"`
        /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string $version" $PRODUCT_SETTINGS_PATH
        /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $vv" $PRODUCT_SETTINGS_PATH

    - name: install depencies
      run: |
        pod install
        npm install -g appdmg
    - name: build
      env:
        sparkle_key: ${{ secrets.sparkle_key }}
        apple_id: ${{ secrets.APPLEID }}
        apple_id_password: ${{ secrets.APPLE_PASSWORD }}
      run: ./scripts/build.sh
    - name: generate hw.zip
      run: |
        ditto -c -k --sequesterRsrc --keepParent apps/hw.app apps/hw.zip
        # rm -r ~/Library/Caches/Sparkle_generate_appcast/*

    - name: upload release file
      uses: AButler/upload-release-assets@v1.0
      with:
        files: 'apps/dmg/hw.dmg'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/upload-artifact@v1
      with:
        name: appcast
        path: ./apps/appcast.xml
